#!/usr/bin/env bash
# Repeatable from-source vLLM build for the DGX Spark (GB10 / sm_121a).
#
# Resolves and records the exact base-image digest and vLLM commit, then builds
# the image tagged with the short vLLM commit (plus :latest). Re-running with the
# same build.lock reproduces the same image.
#
# Usage:
#   ./build.sh                       # build from current vLLM main HEAD
#   ./build.sh --vllm-ref v0.11.0    # build a specific tag/branch/commit
#   ./build.sh --refresh-base        # re-pull cu130-nightly, re-pin its digest
#   ./build.sh --no-cache            # force a clean rebuild
#   ./build.sh --reproduce           # rebuild exactly what build.lock records
set -euo pipefail
cd "$(dirname "$0")"

BASE_REPO="vllm/vllm-openai:cu130-nightly"
VLLM_REPO="https://github.com/vllm-project/vllm.git"
IMAGE_NAME="vllm-spark"
ARCH_LIST="12.1a"

VLLM_REF="main"
REFRESH_BASE=0
NO_CACHE=""
REPRODUCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --vllm-ref)      VLLM_REF="$2"; shift 2 ;;
    --refresh-base)  REFRESH_BASE=1; shift ;;
    --no-cache)      NO_CACHE="--no-cache"; shift ;;
    --reproduce)     REPRODUCE=1; shift ;;
    -h|--help)       sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

export DOCKER_BUILDKIT=1

# --- 1. resolve the base image digest (pin) --------------------------------
if [[ "$REPRODUCE" == 1 && -f build.lock ]]; then
  # shellcheck disable=SC1091
  source build.lock
  echo ">> reproducing build.lock: base=$BASE_DIGEST vllm=$VLLM_COMMIT"
else
  if [[ "$REFRESH_BASE" == 1 ]] || ! docker image inspect "$BASE_REPO" >/dev/null 2>&1; then
    echo ">> pulling base image $BASE_REPO ..."
    docker pull "$BASE_REPO"
  fi
  BASE_DIGEST="$(docker inspect --format '{{index .RepoDigests 0}}' "$BASE_REPO")"

  # --- 2. resolve the vLLM commit to build -------------------------------
  if [[ "$VLLM_REF" =~ ^[0-9a-f]{40}$ ]]; then
    VLLM_COMMIT="$VLLM_REF"
  else
    echo ">> resolving vLLM ref '$VLLM_REF' ..."
    VLLM_COMMIT="$(git ls-remote "$VLLM_REPO" "$VLLM_REF" "refs/tags/$VLLM_REF" "refs/heads/$VLLM_REF" \
                    | head -n1 | cut -f1)"
    [[ -z "$VLLM_COMMIT" ]] && { echo "could not resolve '$VLLM_REF'" >&2; exit 1; }
  fi
fi

SHORT="${VLLM_COMMIT:0:8}"
TAG="${IMAGE_NAME}:${SHORT}"

echo "============================================================"
echo "  base image : $BASE_DIGEST"
echo "  vllm ref   : $VLLM_REF -> $VLLM_COMMIT"
echo "  gpu arch   : $ARCH_LIST (sm_121a / GB10)"
echo "  image tags : $TAG , ${IMAGE_NAME}:latest"
echo "============================================================"

# --- 3. build --------------------------------------------------------------
docker build $NO_CACHE \
  --build-arg "BASE_IMAGE=${BASE_DIGEST}" \
  --build-arg "VLLM_REPO=${VLLM_REPO}" \
  --build-arg "VLLM_REF=${VLLM_COMMIT}" \
  --build-arg "TORCH_CUDA_ARCH_LIST=${ARCH_LIST}" \
  -t "$TAG" -t "${IMAGE_NAME}:latest" \
  .

# --- 4. record provenance --------------------------------------------------
cat > build.lock <<EOF
# Generated by build.sh -- pins for a reproducible rebuild (./build.sh --reproduce)
BASE_DIGEST="$BASE_DIGEST"
VLLM_REF="$VLLM_REF"
VLLM_COMMIT="$VLLM_COMMIT"
ARCH_LIST="$ARCH_LIST"
EOF

echo ">> done. Built $TAG"
echo ">> serve with:  ./run.sh <model-id>"
